import os

from utils import get_package_root
_curr_root = get_package_root('')
word2vec_model_filename = _curr_root.joinpath("data/word2vec_twitter_model.bin")
nrc_lexicon_filename = _curr_root.joinpath("data/lexicon/NRC-Emotion-Lexicon/NRC-Emotion-Lexicon-Wordlevel-v0.92.txt")
vad_lexicon_filename = _curr_root.joinpath("data/lexicon/NRC-VAD-Lexicon/NRC-VAD-Lexicon.txt")
social_lexicon_filename = _curr_root.joinpath("data/lexicon/SocialnessNorms_DiveicaPexmanBinney2021.csv")
vader_lexicon_filename = _curr_root.joinpath("data/lexicon/vader_lexicon.txt")

initialized = False

def initialize():

 default_urls_colname = 'urls'
 default_emojis_colname = 'emojis'
 default_emoticons_colname = 'emoticons'
 default_mentions_colname = 'mentions'
 default_hashtags_colname = 'hashtags'
 default_badwords_colname = 'badwords'
 default_repeated_punctuation_colname = 'repeatedPunctuation'
 default_uppercase_words_colname = 'uppercaseWords'

 single_feature_names_dict = {default_urls_colname: 'url',
                              default_emojis_colname: 'emoji',
                              default_emoticons_colname: 'emoticon',
                              default_mentions_colname: 'mention',
                              default_hashtags_colname: 'hashtag',
                              default_badwords_colname: 'badword',
                              default_repeated_punctuation_colname: 'punctuation',
                              default_uppercase_words_colname: 'word'}


 default_textual_columns = ['text', default_urls_colname, default_emojis_colname, default_emoticons_colname,
                            default_mentions_colname, default_hashtags_colname, default_badwords_colname,
                            default_repeated_punctuation_colname, default_uppercase_words_colname, 'clean_text']
 default_texts_columns = ['text', 'clean_text']
 
 ALL_FEATURES_COLUMNS = ['tokens_count',
 'sentences_count',
 'spacy_EVENT_count',
 'spacy_FAC_count',
 'spacy_GPE_count',
 'spacy_LANGUAGE_count',
 'spacy_LAW_count',
 'spacy_LOC_count',
 'spacy_MONEY_count',
 'spacy_NORP_count',
 'spacy_ORG_count',
 'spacy_PERSON_count',
 'spacy_PRODUCT_count',
 'spacy_WORK_OF_ART_count',
 'spacy_TIME_count',
 'spacy_NUMERICAL_count',
 'spacy_entities_count',
 'negative_emojis_count',
 'positive_emojis_count',
 'neutral_emojis_count',
 'emojis_count',
 'negative_emoticons_count',
 'positive_emoticons_count',
 'neutral_emoticons_count',
 'emoticons_count',
 'urls_count',
 'mentions_count',
 'repeatedPunctuation_count',
 'hashtags_count',
 'badwords_count',
 'uppercaseWords_count',
 'names_count',
 'adjectives_count',
 'verbs_count',
 'adverbs_count',
 'detoxify_toxicity',
 'detoxify_severe_toxicity',
 'detoxify_obscene',
 'detoxify_identity_attack',
 'detoxify_insult',
 'detoxify_threat',
 'detoxify_sexual_explicit',
 'pattern_modality',
 'vader_sentiment',
 'eng_spacysentiment',
 'pattern_sentiment',
 'pattern_subjectivity',
 'trust',
 'positive',
 'negative',
 'joy',
 'surprise',
 'anger',
 'fear',
 'anticipation',
 'sadness',
 'disgust',
 'strong_valence_tokens_ratio',
 'valence_mean',
 'strong_arousal_tokens_ratio',
 'arousal_mean',
 'strong_dominance_tokens_ratio',
 'dominance_mean',
 'strong_socialness_tokens_ratio',
 'socialness_mean',
 'bias_care',
 'bias_loyalty',
 'bias_fairness',
 'bias_sanctity',
 'bias_authority',
 'intensity_care',
 'intensity_loyalty',
 'intensity_fairness',
 'intensity_sanctity',
 'intensity_authority',
 'care.vice',
 'care.virtue',
 'loyalty.vice',
 'loyalty.virtue',
 'fairness.vice',
 'fairness.virtue',
 'sanctity.vice',
 'sanctity.virtue',
 'authority.vice',
 'authority.virtue',
 'Populism',
 'PeopleCentrism',
 'AntiElitism',
 'EmotionalAppeal',
 'word_feat_0',
 'word_feat_1',
 'word_feat_2',
 'word_feat_3',
 'word_feat_4',
 'word_feat_5',
 'word_feat_6',
 'word_feat_7',
 'word_feat_8',
 'word_feat_9',
 'word_feat_10',
 'word_feat_11',
 'word_feat_12',
 'word_feat_13',
 'word_feat_14',
 'word_feat_15',
 'word_feat_16',
 'word_feat_17',
 'word_feat_18',
 'word_feat_19']


 emoticons_list = [':)',
                   ':-)',
                   ':)',
                   ':-]',
                   ':]',
                   ':-3',
                   ':3',
                   ':->',
                   ':>',
                   '8-)',
                   '8)',
                   ':-}',
                   ':}',
                   ':o)',
                   ':c)',
                   ':^)',
                   '=]',
                   '=)',
                   ':-D',
                   ':D',
                   '8-D',
                   '8D',
                   'x-D',
                   'xD',
                   'X-D',
                   'XD',
                   '=D',
                   '=3',
                   'B^D',
                   ':-))',
                   ':-(',
                   ':(',
                   ':-c',
                   ':c',
                   ':-<',
                   ':<',
                   ':-[',
                   ':[',
                   ':-||',
                   '>:[',
                   ':{',
                   ':@',
                   '>:(',
                   "('_')",
                   '(/_;)',
                   '(T_T)',
                   '(;_;)',
                   '(;_;',
                   '(;_:)',
                   '(;O;)',
                   '(:_;)',
                   '(ToT)',
                   '(Ｔ▽Ｔ)',
                   ';_;',
                   ';-;',
                   ';n;',
                   ';;',
                   'Q.Q',
                   'T.T',
                   'TnT',
                   'QQ',
                   'Q_Q',
                   '(ー_ー)!!',
                   '(-.-)',
                   '(-_-)',
                   '(一一)',
                   '(；一_一)',
                   '＼(~o~)／',
                   '＼(^o^)／',
                   '＼(-o-)／',
                   'ヽ(^。^)ノ',
                   'ヽ(^o^)丿',
                   '(*^0^*)',
                   ":'-(",
                   ":'(",
                   ":'-)",
                   ":')",
                   "D-':",
                   'D:<',
                   'D:',
                   'D8',
                   'D;',
                   'D=',
                   'DX',
                   ':-O',
                   ':O',
                   ':-o',
                   ':o',
                   ':-0',
                   '8-0',
                   '>:O',
                   '(￣□￣;)',
                   '°o°',
                   '°O°',
                   ':O',
                   'o_0',
                   'o.O',
                   '(o.o)',
                   'oO',
                   ':-*',
                   ':*',
                   ':×',
                   ';-)',
                   ';)',
                   '*-)',
                   '*)',
                   ';-]',
                   ';]',
                   ';^)',
                   ':-,',
                   ';D',
                   ':-P',
                   ':P',
                   'X-P',
                   'XP',
                   'x-p',
                   'xp',
                   ':-p',
                   ':p',
                   ':-Þ',
                   ':Þ',
                   ':-þ',
                   ':þ',
                   ':-b',
                   ':b',
                   'd:',
                   '=p',
                   '>:P',
                   ':-/',
                   ':/',
                   ':-.',
                   '>:\\',
                   '>:/',
                   ':\\',
                   '=/',
                   '=\\',
                   ':L',
                   '=L',
                   ':S',
                   ':-|',
                   ':|',
                   ':$',
                   '://)',
                   '://3',
                   '(^^ゞ',
                   '(^_^;)',
                   '(-_-;)',
                   '(~_~;)',
                   '(・.・;)',
                   '(・_・;)',
                   '(・・;)^^',
                   ';^_^;',
                   '(#^.^#)',
                   '(^^;)',
                   ':-X',
                   ':X',
                   ':-#',
                   ':#',
                   ':-&',
                   ':&',
                   'O:-)',
                   'O:)',
                   '0:-3',
                   '0:3',
                   '0:-)',
                   '0:)',
                   '0;^)',
                   '>:-)',
                   '>:)',
                   '}:-)',
                   '}:)',
                   '3:-)',
                   '3:)',
                   '>;)',
                   '>:3',
                   '>;3',
                   ':‑J',
                   '#‑)',
                   '|;-)',
                   '|-O',
                   '%-)',
                   '%)',
                   ':-###..',
                   ':###.',
                   '<:-|',
                   '(>_<)',
                   '(>_<)>',
                   '((+_+))',
                   '(+o+)',
                   '(°°)',
                   '(°-°)',
                   '(°.°)',
                   '(°_°)',
                   '(°_°>)',
                   '(°レ°)',
                   '^_^',
                   '(°o°)',
                   '(^_^)/',
                   '(^O^)／',
                   '(^o^)／',
                   '(^^)/',
                   '(-∇-)/',
                   '(/-ヮ-)/',
                   '(^o^)丿',
                   '∩(·ω·)∩',
                   '(·ω·)',
                   '^ω^',
                   '"(-""-)"',
                   '(ーー゛)',
                   '(^_^メ)',
                   '(-_-メ)',
                   '(~_~メ)',
                   '(－－〆)',
                   '(・へ・)',
                   '(｀´)',
                   '<`～´>',
                   '<`ヘ´>',
                   '(ーー;)']

 meaning_list = ['smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'smile',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'laugh',
                 'very happy',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'sad',
                 'shame',
                 'shame',
                 'shame',
                 'shame',
                 'shame',
                 'exited',
                 'exited',
                 'exited',
                 'exited',
                 'exited',
                 'exited',
                 'crying',
                 'crying',
                 'tears happiness',
                 'tears happiness',
                 'disgust',
                 'disgust',
                 'disgust',
                 'disgust',
                 'disgust',
                 'disgust',
                 'disgust',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'o_o shock',
                 'shock',
                 'shock',
                 'shock',
                 'shock',
                 'kiss',
                 'kiss',
                 'kiss',
                 'smirk',
                 'smirk',
                 'smirk',
                 'smirk',
                 'smirk',
                 'smirk',
                 'smirk',
                 'smirk smirk',
                 'smirk smirk',
                 'cheeky smirk',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'cheeky',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'annoyed',
                 'indecision annoyed',
                 'indecision',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'embarrassed',
                 'shut',
                 'shut',
                 'shut',
                 'shut',
                 'shut',
                 'shut',
                 'innocent',
                 'innocent',
                 'innocent',
                 'innocent',
                 'innocent',
                 'innocent',
                 'innocent',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'evil',
                 'tongue in cheek evil',
                 'party all night evil',
                 'cool',
                 'cool',
                 'drunk',
                 'drunk',
                 'sick',
                 'sick',
                 'dumb',
                 'troubled',
                 'troubled',
                 'confused',
                 'confused',
                 'confused',
                 'confused',
                 'confused',
                 'confused',
                 'confused',
                 'confused',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'joyful',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried',
                 'worried']

 # emoticon_dict = dict(zip(emoticon_lst, meaning_lst))
 def get_emoticons_from_vader_lexicon(vader_lexicon_filename: str,
                                      return_scores: bool = False) -> list[str] or dict[str, float]:
  import pandas as pd
  import string
  with open(vader_lexicon_filename, 'r') as f:
   tmp_l = f.read().splitlines()
   f.close()

  vader_sentiment_dict = {e[0]: list(map(lambda elem: eval(elem), e[1:])) for e in
                          list(map(lambda x: x.split('\t'), tmp_l))}
  vader_sentiment_df = pd.DataFrame(index=vader_sentiment_dict.keys(), data=vader_sentiment_dict.values(),
                                    columns=['mean_score', 'std', 'scores'])
  vader_emoticons = vader_sentiment_df[(vader_sentiment_df.index.str.contains(r'[{}]'.format(string.punctuation))) | (
   vader_sentiment_df.index.str.lower().isin(['xd', 'xp']))].index.drop(
   ['once-in-a-lifetime', 'self-confident', 'short-sighted',
    'short-sightedness', 'son-of-a-bitch', 'sweet<3', '^urs', "can't stand", 'cover-up', 'aug-00', 'h&k', 'hho1/2k',
    'j/j', 'j/k', 'j/p', 'j/t', 'j/w', 'l&r', '0:03']).values
  emoticons_df = vader_sentiment_df.loc[vader_emoticons]
  if return_scores:
   from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
   an = SentimentIntensityAnalyzer()
   emoticons_df = pd.concat([emoticons_df,
                             pd.Series(emoticons_df.index.map(lambda t: an.polarity_scores(t))).apply(
                              pd.Series).set_index(emoticons_df.index)]
                            , axis=1)
   return dict(*emoticons_df[['compound']].to_dict().values())
  return emoticons_df.index.values
  
  
  #global vader_lexicon_filename
 emoticons_list_vader = get_emoticons_from_vader_lexicon(return_scores=True, vader_lexicon_filename=vader_lexicon_filename)

 badwords_LDNOOBW = ['2g1c', '2 girls 1 cup', 'alabama hot pocket', 'alaskan pipeline', 'anal',
                     'anilingus', 'apeshit', 'arsehole', 'ass', 'asshole', 'assmunch', 'baby batter', 'baby juice',
                     'ball gag', 'ball gravy', 'ball kicking', 'ball licking',
                     'ball sack', 'ball sucking', 'bareback', 'bastard', 'bastardo',
                     'bastinado', 'beaner', 'beaners', 'beaver cleaver', 'beaver lips', 'big knockers', 'big tits',
                     'bimbos',
                     'bitch', 'bitches', 'black cock', 'blowjob', 'blow job', 'blow your load', 'blue waffle',
                     'blumpkin', 'bollocks', 'boner', 'boob', 'boobs', 'brown showers',
                     'bukkake', 'bulldyke', 'bullshit', 'bung hole', 'bunghole', 'busty', 'butt',
                     'buttcheeks', 'butthole', 'camel toe', 'camslut', 'camwhore', 'carpet muncher',
                     'carpetmuncher', 'chocolate rosebuds', 'circlejerk', 'cleveland steamer', 'clit',
                     'clusterfuck', 'cock', 'cocks', 'coprolagnia', 'coprophilia', 'cornhole',
                     'coon', 'coons', 'creampie', 'cum', 'cumming', 'cumshot', 'cumshots', 'cunnilingus', 'cunt',
                     'darkie',
                     'date rape', 'daterape', 'deep throat', 'deepthroat', 'dick', 'dingleberry',
                     'dingleberries', 'dirty pillows', 'dirty sanchez', 'doggie style', 'doggiestyle', 'doggy style',
                     'doggystyle', 'dog style', 'dommes', 'donkey punch', 'double penetration', 'dp action', 'dry hump',
                     'dvda',
                     'eat my ass', 'fag', 'faggot', 'felch', 'feltch', 'female squirting', 'fingerbang', 'fisting',
                     'frotting', 'fuck', 'fuck buttons', 'fuckin', 'fucking', 'fucktards', 'fudge packer',
                     'fudgepacker', 'gangbang',
                     'gang bang', 'goatcx', 'goatse', 'god damn', 'gokkun', 'golden shower', 'goodpoop', 'goregasm',
                     'hand job', 'handjob', 'honkey', 'hooker', 'hot carl', 'huge fat', 'humping', 'jack off',
                     'jail bait', 'jailbait',
                     'jelly donut', 'jerk off', 'jigaboo', 'jiggaboo', 'jiggerboo', 'jizz', 'juggs', 'kike', 'kinkster',
                     'kinky',
                     'knobbing', 'make me come', 'male squirting', 'masturbate', 'masturbating', 'masturbation',
                     'mong', 'motherfucker', 'muff diver', 'muffdiving', 'negro', 'nigga', 'nigger', 'nig nog',
                     'nutten', 'octopussy', 'one cup two girls', 'one guy one jar', 'paedophile', 'paki', 'pedobear',
                     'pedophile', 'phone sex', 'piece of shit', 'pikey', 'pissing', 'piss pig', 'pisspig',
                     'pole smoker',
                     'poof', 'poon', 'poontang', 'punany', 'poop chute', 'poopchute', 'pthc', 'pussy', 'queaf',
                     'queef', 'quim', 'raghead', 'raging boner', 'rimjob', 'rimming',
                     'rosy palm', 'rusty trombone', 'scat', 'schlong', 'shaved beaver', 'shaved pussy', 'shemale',
                     'shit', 'shitblimp', 'shitty', 'shota', 'shrimping', 'skeet', 'slanteye', 'slut',
                     'snowballing', 'spastic', 'spic', 'splooge', 'splooge moose', 'spooge', 'spunk',
                     'suck', 'sucks', 'suicide girls', 'swastika', 'tea bagging', 'throating', 'thumbzilla',
                     'tit', 'tits', 'titties', 'titty', 'tosser', 'towelhead', 'tranny',
                     'tub girl', 'tubgirl', 'tushy', 'twat', 'two girls one cup', 'upskirt', 'urethra play',
                     'wank', 'wetback', 'whore', 'wrinkled starfish', 'yellow showers', 'zoophilia', 'ðŸ–•']

 for v in locals().copy():
  globals()[v]=locals()[v]





if not initialized:
 initialize()
 initialized = True
#for var in curr_vars:
# globals()[var] = curr_vars[var]